# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

#[[menu.main]]
#  name = "Bio"
#  url = "bio"
#  weight = 2

[[menu.main]]
  name = "News"
  url = "#news"
  weight = 2

[[menu.main]]
  name = "Papers"
  url = "#papers" # "#featured" v4.0
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 5

  [[menu.main]]
  name = "Talks"
  url = "#talks"
  weight = 6

#[[menu.main]]
#  name = "Tutorials"
#  url = "/tutorial/"
#  weight = 5

[[menu.main]]
  name = "Group"
  url = "/group"
  weight = 7

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 8

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
